[project]
authors = ["RenaudLN <renaudlaine31@gmail.com>"]
channels = ["conda-forge"]
name = "plotly-oftw"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
dash = "<3"
plotly = ">=6"
polars = ">=1.24.0,<2"
